using System.Net;
using System.Text;

namespace ZompiercerLAN
{
    // Built-in internet relay of this build: address, port, pinned certificate
    // fingerprint and server access key. The values live masked in
    // RelayDefaults.Data.cs (generated by tools/relay-defaults.ps1), not as plain
    // text in the DLL or in the BepInEx config. This is obfuscation, not
    // protection: the DLL holds everything needed to recover them, and the
    // address is visible in the player's network connections.
    internal static partial class RelayDefaults
    {
        // False in builds from the public source, which ship an empty RelayDefaults.Data.cs:
        // they play over the internet only through a custom relay ([Relay] Custom* settings).
        internal static bool Available { get { return ServerData.Length != 0; } }
        internal static IPAddress Server { get { return IPAddress.Parse(Encoding.ASCII.GetString(Unmask(ServerData))); } }
        internal static int Port { get { return PortValue; } }
        internal static byte[] Fingerprint { get { return Unmask(FingerprintData); } }
        internal static string AccessKey { get { return Encoding.UTF8.GetString(Unmask(AccessKeyData)); } }

        internal static LanRelayOptions Create(string room)
        {
            return new LanRelayOptions { Server = Server, Port = Port, Fingerprint = Fingerprint, AccessKey = AccessKey, Room = room ?? "" };
        }

        private static byte[] Unmask(byte[] data)
        {
            var result = new byte[data.Length];
            for (int i = 0; i < data.Length; i++) result[i] = (byte)(data[i] ^ Mask[i % Mask.Length] ^ (byte)(i * 131));
            return result;
        }
    }
}
